/**
 * The normalized shape every accounting export is parsed into.
 *
 * Deliberately small, and deliberately not a superset of any one package's schema. Every
 * accounting system models the same double entry underneath and disagrees about everything
 * above it; a model that tried to cover all of them would be mostly empty fields and would
 * still be wrong for the next one. What is here is what every general ledger has and what
 * every spend or revenue question needs.
 */

/** How the source classifies an account. Reported as-is; never inferred from the number. */
export type AccountType =
  | "asset"
  | "liability"
  | "equity"
  | "income"
  | "expense"
  | "cost-of-sales"
  | "other-income"
  | "other-expense"
  | "unknown";

export interface Account {
  /** The source's account code, e.g. `6-4390`. Stable, and how lines reference it. */
  code: string;
  name: string;
  type: AccountType;
  /** Parent account code, where the source models a hierarchy. */
  parent?: string;
  /** A rollup rather than a postable account. */
  header: boolean;
  /** Tax treatment code as the source records it, e.g. `GST`, `FRE`. Never interpreted here. */
  taxCode?: string;
  active: boolean;
}

export interface JournalLine {
  /**
   * Groups the lines of one transaction. THE most important field here: without it the
   * postings of a sale cannot be tied to each other, and questions like "revenue by
   * customer" become unanswerable, because the customer is named on the receivable line
   * while the amount lives on the income line.
   */
  transactionRef: string;
  /** ISO date, `YYYY-MM-DD`. */
  date: string;
  accountCode: string;
  /** Signed. Positive is a debit, negative a credit, matching the source's convention. */
  amount: number;
  /**
   * The source's own narration, verbatim. Usually names a counterparty, sometimes a bank
   * feed's raw merchant string. Kept unparsed: it is evidence, and interpreting it is a
   * separate, fallible step that must not overwrite what the books actually say.
   */
  description: string;
  /** Per-line id where the source provides one. */
  lineId?: string;
}

/**
 * What a single export file covers.
 *
 * Present so an aggregate can refuse to answer outside it. Asking what was spent in a
 * period the file does not cover must produce "no data for that period", never zero — a
 * zero looks like a fact, and in accounting a wrong fact is worse than an admitted gap.
 */
export interface Coverage {
  /** Entity the books belong to, as named by the source. */
  entity: string;
  /** ISO date, inclusive. */
  from: string;
  /** ISO date, inclusive. */
  to: string;
  /** Which adapter produced this, e.g. `myob-ceedata`. */
  source: string;
}

export interface Ledger {
  coverage: Coverage;
  accounts: Account[];
  lines: JournalLine[];
}

/**
 * A parse that got far enough to be useful, plus everything it could not use.
 *
 * Rejected rows are returned rather than dropped or thrown on. A bookkeeping export is
 * generated by someone else's software and will contain shapes we have not seen; failing
 * the whole import for one unparseable line would make the realm brittle, while silently
 * skipping it would make the totals quietly wrong. Surfacing them lets the caller report
 * "imported 2,338 of 2,340 lines" and say which two.
 */
export interface ParseResult {
  ledger: Ledger;
  rejected: RejectedRow[];
  /**
   * Questions only the user can settle.
   *
   * Separate from [rejected] because these are not faults. A rejected row is something the
   * file got wrong; a clarification is something the file simply does not say, where
   * guessing is cheap to do and expensive to be wrong about. The parser stays pure and
   * merely reports them — asking belongs to whatever is driving the import, which is the
   * only layer that can hold a conversation.
   */
  clarifications: Clarification[];
}

/**
 * Something the import should ask about rather than assume.
 *
 * Carries what the parser will do if nobody answers, because an unanswered question must
 * still leave a usable result — an import that blocks forever on a prompt nobody sees is
 * worse than one that proceeds on a stated assumption.
 */
export interface Clarification {
  /** Stable id, so an answer can be matched back and remembered. */
  id: string;
  question: string;
  options: ClarificationOption[];
  /** Why we cannot settle it from the file. */
  reason: string;
  /** What was assumed in the absence of an answer, in plain terms. */
  assumed: string;
}

export interface ClarificationOption {
  id: string;
  label: string;
  /** What choosing this would mean for the data, so the choice is informed. */
  consequence: string;
}

export interface RejectedRow {
  /** 1-based line number in the source file. */
  line: number;
  /** Why it could not be used, in terms a user could act on. */
  reason: string;
  /** The offending text, truncated. */
  raw: string;
}
